name: my-flask-app
version: 1.0

services:
  - name: web
    type: web
    instance_type: nano
    port: 8000

    build:
      type: python

    run:
      command: uwsgi --ini uwsgi.ini

    env:
      FLASK_ENV: production
