name: my-flask-app
version: 1.0

services:
  - name: web
    type: web
    instance_type: nano
    port: 5000

    build:
      type: python

    run:
      command: gunicorn app:app

    env:
      FLASK_ENV: production
